### ISSUE TITLE
Try proposal process

### ISSUE THREAD

**Issue by ChrisCho-H** [hippocrat-dao/hippo-protocol#44]
We need to figure out `gov` modules. It would be helpful to try sending proposal, voting and updating in devnet or testnet.
It's crucial to apply upgrades or consensus changes.
Reference: https://www.mintscan.io/cosmos/proposals
cc. @devmasme @0114kek

**Comment by 0114kek** [comment]
![image](https://github.com/user-attachments/assets/a40b879d-53ff-41e7-b9be-778f61a40aab)

Thanks, I also succeed proposing and voting using cli. I found some reference for proposing&voting with js
https://cosmos.github.io/cosmjs/latest/stargate/interfaces/GovExtension.html
https://github.com/cosmos/cosmjs/issues/1205
